// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SSMessage_MessageType int32

const (
	SSMessage_UNKNOWN   SSMessage_MessageType = 0
	SSMessage_REQUEST   SSMessage_MessageType = 1
	SSMessage_RESPONSE  SSMessage_MessageType = 2
	SSMessage_NOTIFY    SSMessage_MessageType = 3
	SSMessage_BROADCAST SSMessage_MessageType = 4
)

var SSMessage_MessageType_name = map[int32]string{
	0: "UNKNOWN",
	1: "REQUEST",
	2: "RESPONSE",
	3: "NOTIFY",
	4: "BROADCAST",
}
var SSMessage_MessageType_value = map[string]int32{
	"UNKNOWN":   0,
	"REQUEST":   1,
	"RESPONSE":  2,
	"NOTIFY":    3,
	"BROADCAST": 4,
}

func (x SSMessage_MessageType) String() string {
	return proto.EnumName(SSMessage_MessageType_name, int32(x))
}
func (SSMessage_MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

// SSMessage Server Message结构
type SSMessage struct {
	SessionID string                `protobuf:"bytes,1,opt,name=sessionID" json:"sessionID,omitempty"`
	SrcSID    int32                 `protobuf:"varint,2,opt,name=srcSID" json:"srcSID,omitempty"`
	SrcType   int32                 `protobuf:"varint,3,opt,name=srcType" json:"srcType,omitempty"`
	DestSID   int32                 `protobuf:"varint,4,opt,name=destSID" json:"destSID,omitempty"`
	DestType  int32                 `protobuf:"varint,5,opt,name=destType" json:"destType,omitempty"`
	SeqID     int32                 `protobuf:"varint,6,opt,name=seqID" json:"seqID,omitempty"`
	MessageID int32                 `protobuf:"varint,7,opt,name=messageID" json:"messageID,omitempty"`
	MsgType   SSMessage_MessageType `protobuf:"varint,8,opt,name=msgType,enum=pb.SSMessage_MessageType" json:"msgType,omitempty"`
	TransID   string                `protobuf:"bytes,9,opt,name=transID" json:"transID,omitempty"`
	Uid       int32                 `protobuf:"varint,10,opt,name=uid" json:"uid,omitempty"`
	BodySize  int32                 `protobuf:"varint,11,opt,name=bodySize" json:"bodySize,omitempty"`
	Body      []byte                `protobuf:"bytes,12,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *SSMessage) Reset()                    { *m = SSMessage{} }
func (m *SSMessage) String() string            { return proto.CompactTextString(m) }
func (*SSMessage) ProtoMessage()               {}
func (*SSMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *SSMessage) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *SSMessage) GetSrcSID() int32 {
	if m != nil {
		return m.SrcSID
	}
	return 0
}

func (m *SSMessage) GetSrcType() int32 {
	if m != nil {
		return m.SrcType
	}
	return 0
}

func (m *SSMessage) GetDestSID() int32 {
	if m != nil {
		return m.DestSID
	}
	return 0
}

func (m *SSMessage) GetDestType() int32 {
	if m != nil {
		return m.DestType
	}
	return 0
}

func (m *SSMessage) GetSeqID() int32 {
	if m != nil {
		return m.SeqID
	}
	return 0
}

func (m *SSMessage) GetMessageID() int32 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *SSMessage) GetMsgType() SSMessage_MessageType {
	if m != nil {
		return m.MsgType
	}
	return SSMessage_UNKNOWN
}

func (m *SSMessage) GetTransID() string {
	if m != nil {
		return m.TransID
	}
	return ""
}

func (m *SSMessage) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SSMessage) GetBodySize() int32 {
	if m != nil {
		return m.BodySize
	}
	return 0
}

func (m *SSMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*SSMessage)(nil), "pb.SSMessage")
	proto.RegisterEnum("pb.SSMessage_MessageType", SSMessage_MessageType_name, SSMessage_MessageType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Message service

type MessageClient interface {
	// 定义Request方法
	Request(ctx context.Context, opts ...grpc.CallOption) (Message_RequestClient, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) Request(ctx context.Context, opts ...grpc.CallOption) (Message_RequestClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Message_serviceDesc.Streams[0], c.cc, "/pb.Message/Request", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageRequestClient{stream}
	return x, nil
}

type Message_RequestClient interface {
	Send(*SSMessage) error
	Recv() (*SSMessage, error)
	grpc.ClientStream
}

type messageRequestClient struct {
	grpc.ClientStream
}

func (x *messageRequestClient) Send(m *SSMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageRequestClient) Recv() (*SSMessage, error) {
	m := new(SSMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Message service

type MessageServer interface {
	// 定义Request方法
	Request(Message_RequestServer) error
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_Request_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServer).Request(&messageRequestServer{stream})
}

type Message_RequestServer interface {
	Send(*SSMessage) error
	Recv() (*SSMessage, error)
	grpc.ServerStream
}

type messageRequestServer struct {
	grpc.ServerStream
}

func (x *messageRequestServer) Send(m *SSMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageRequestServer) Recv() (*SSMessage, error) {
	m := new(SSMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Message",
	HandlerType: (*MessageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Request",
			Handler:       _Message_Request_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x6f, 0xaa, 0x40,
	0x10, 0xc6, 0x5d, 0x40, 0x90, 0x51, 0x5f, 0xc8, 0xe6, 0xe5, 0x65, 0x9f, 0xe9, 0x81, 0x78, 0xe2,
	0x52, 0xd2, 0xe8, 0xa5, 0x57, 0x2d, 0x34, 0x21, 0x4d, 0xc1, 0xee, 0x62, 0x9a, 0xf6, 0x26, 0xba,
	0x31, 0x1e, 0x14, 0x64, 0xf1, 0x60, 0xff, 0xa2, 0xfe, 0x99, 0xcd, 0x2e, 0xa0, 0xf5, 0xc4, 0xf7,
	0x9b, 0x6f, 0x87, 0xf9, 0x26, 0x03, 0xc3, 0x3d, 0x17, 0x62, 0xb5, 0xe5, 0x7e, 0x51, 0xe6, 0x55,
	0x8e, 0xb5, 0x22, 0x1b, 0x7f, 0xeb, 0x60, 0x33, 0xf6, 0x5a, 0xd7, 0xf1, 0x1d, 0xd8, 0x82, 0x0b,
	0xb1, 0xcb, 0x0f, 0x51, 0x40, 0x90, 0x8b, 0x3c, 0x9b, 0x5e, 0x0b, 0xf8, 0x1f, 0x98, 0xa2, 0x5c,
	0xb3, 0x28, 0x20, 0x9a, 0x8b, 0xbc, 0x2e, 0x6d, 0x08, 0x13, 0xb0, 0x44, 0xb9, 0x4e, 0xcf, 0x05,
	0x27, 0xba, 0x32, 0x5a, 0x94, 0xce, 0x86, 0x8b, 0x4a, 0xb6, 0x18, 0xb5, 0xd3, 0x20, 0x1e, 0x41,
	0x4f, 0x4a, 0xd5, 0xd4, 0x55, 0xd6, 0x85, 0xf1, 0x5f, 0xe8, 0x0a, 0x7e, 0x8c, 0x02, 0x62, 0x2a,
	0xa3, 0x06, 0x99, 0xad, 0x89, 0x1f, 0x05, 0xc4, 0x52, 0xce, 0xb5, 0x80, 0xa7, 0x60, 0xed, 0xc5,
	0x56, 0xfd, 0xae, 0xe7, 0x22, 0xef, 0xcf, 0xe4, 0xbf, 0x5f, 0x64, 0xfe, 0x65, 0x33, 0xbf, 0xf9,
	0xca, 0x07, 0xb4, 0x7d, 0x29, 0xe3, 0x55, 0xe5, 0xea, 0x20, 0xa2, 0x80, 0xd8, 0x6a, 0xd9, 0x16,
	0xb1, 0x03, 0xfa, 0x69, 0xb7, 0x21, 0xa0, 0xc6, 0x48, 0x29, 0x03, 0x67, 0xf9, 0xe6, 0xcc, 0x76,
	0x5f, 0x9c, 0xf4, 0xeb, 0xc0, 0x2d, 0x63, 0x0c, 0x86, 0xd4, 0x64, 0xe0, 0x22, 0x6f, 0x40, 0x95,
	0x1e, 0x2f, 0xa0, 0xff, 0x6b, 0x26, 0xee, 0x83, 0xb5, 0x8c, 0x5f, 0xe2, 0xe4, 0x3d, 0x76, 0x3a,
	0x12, 0x68, 0xf8, 0xb6, 0x0c, 0x59, 0xea, 0x20, 0x3c, 0x80, 0x1e, 0x0d, 0xd9, 0x22, 0x89, 0x59,
	0xe8, 0x68, 0x18, 0xc0, 0x8c, 0x93, 0x34, 0x7a, 0xfe, 0x70, 0x74, 0x3c, 0x04, 0x7b, 0x4e, 0x93,
	0x59, 0xf0, 0x34, 0x63, 0xa9, 0x63, 0x4c, 0x1e, 0xc1, 0x6a, 0xef, 0x74, 0x0f, 0x16, 0xe5, 0xc7,
	0x13, 0x17, 0x15, 0x1e, 0xde, 0xec, 0x39, 0xba, 0xc5, 0x71, 0xc7, 0x43, 0x0f, 0x68, 0x6e, 0x7c,
	0x6a, 0x45, 0x96, 0x99, 0xea, 0xea, 0xd3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xfe, 0x0b,
	0xca, 0x06, 0x02, 0x00, 0x00,
}
