// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package body is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
	ResponseCode
	UserRegisterReq
	UserRegisterResp
	UserLoginReq
	UserLoginResp
*/
package body

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginType int32

const (
	LoginType_UNKNOWN  LoginType = 0
	LoginType_ACCOUNT  LoginType = 1
	LoginType_PHONEPWD LoginType = 2
	LoginType_PHONESMS LoginType = 3
	LoginType_QQ       LoginType = 4
	LoginType_WX       LoginType = 5
)

var LoginType_name = map[int32]string{
	0: "UNKNOWN",
	1: "ACCOUNT",
	2: "PHONEPWD",
	3: "PHONESMS",
	4: "QQ",
	5: "WX",
}
var LoginType_value = map[string]int32{
	"UNKNOWN":  0,
	"ACCOUNT":  1,
	"PHONEPWD": 2,
	"PHONESMS": 3,
	"QQ":       4,
	"WX":       5,
}

func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}
func (LoginType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// User 结构
type User struct {
	Uid      int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Account  string `protobuf:"bytes,4,opt,name=account" json:"account,omitempty"`
	Nickname string `protobuf:"bytes,5,opt,name=nickname" json:"nickname,omitempty"`
	Password string `protobuf:"bytes,6,opt,name=password" json:"password,omitempty"`
	Phone    string `protobuf:"bytes,7,opt,name=phone" json:"phone,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ResponseCode struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *ResponseCode) Reset()                    { *m = ResponseCode{} }
func (m *ResponseCode) String() string            { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()               {}
func (*ResponseCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseCode) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseCode) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// UserRegisterReq Server Message结构
type UserRegisterReq struct {
	Account   string    `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Uid       int64     `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Phone     string    `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	LoginType LoginType `protobuf:"varint,4,opt,name=loginType,enum=body.LoginType" json:"loginType,omitempty"`
	Password  string    `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Token     string    `protobuf:"bytes,6,opt,name=token" json:"token,omitempty"`
	SmsText   string    `protobuf:"bytes,7,opt,name=smsText" json:"smsText,omitempty"`
}

func (m *UserRegisterReq) Reset()                    { *m = UserRegisterReq{} }
func (m *UserRegisterReq) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterReq) ProtoMessage()               {}
func (*UserRegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserRegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserRegisterReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserRegisterReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserRegisterReq) GetLoginType() LoginType {
	if m != nil {
		return m.LoginType
	}
	return LoginType_UNKNOWN
}

func (m *UserRegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegisterReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserRegisterReq) GetSmsText() string {
	if m != nil {
		return m.SmsText
	}
	return ""
}

type UserRegisterResp struct {
	Code *ResponseCode `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	User *User         `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *UserRegisterResp) Reset()                    { *m = UserRegisterResp{} }
func (m *UserRegisterResp) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterResp) ProtoMessage()               {}
func (*UserRegisterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserRegisterResp) GetCode() *ResponseCode {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *UserRegisterResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// UserLoginReq Server Message结构
type UserLoginReq struct {
	Account   string    `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Uid       int64     `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Phone     string    `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	LoginType LoginType `protobuf:"varint,4,opt,name=loginType,enum=body.LoginType" json:"loginType,omitempty"`
	Password  string    `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Token     string    `protobuf:"bytes,6,opt,name=token" json:"token,omitempty"`
	SmsText   string    `protobuf:"bytes,7,opt,name=smsText" json:"smsText,omitempty"`
}

func (m *UserLoginReq) Reset()                    { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string            { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()               {}
func (*UserLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserLoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserLoginReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserLoginReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserLoginReq) GetLoginType() LoginType {
	if m != nil {
		return m.LoginType
	}
	return LoginType_UNKNOWN
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserLoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserLoginReq) GetSmsText() string {
	if m != nil {
		return m.SmsText
	}
	return ""
}

type UserLoginResp struct {
	Code *ResponseCode `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	User *User         `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *UserLoginResp) Reset()                    { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string            { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()               {}
func (*UserLoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserLoginResp) GetCode() *ResponseCode {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *UserLoginResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "body.User")
	proto.RegisterType((*ResponseCode)(nil), "body.ResponseCode")
	proto.RegisterType((*UserRegisterReq)(nil), "body.UserRegisterReq")
	proto.RegisterType((*UserRegisterResp)(nil), "body.UserRegisterResp")
	proto.RegisterType((*UserLoginReq)(nil), "body.UserLoginReq")
	proto.RegisterType((*UserLoginResp)(nil), "body.UserLoginResp")
	proto.RegisterEnum("body.LoginType", LoginType_name, LoginType_value)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x93, 0xcd, 0x6e, 0xe2, 0x30,
	0x14, 0x85, 0xc7, 0xf9, 0x03, 0x2e, 0xcc, 0x60, 0x59, 0xb3, 0xb0, 0x66, 0x31, 0x42, 0x59, 0x8c,
	0xd0, 0x48, 0xc3, 0x82, 0x99, 0x17, 0x98, 0xd2, 0x4a, 0x95, 0xda, 0x06, 0x08, 0xa0, 0x54, 0xec,
	0x42, 0x62, 0xd1, 0x08, 0x12, 0xa7, 0x71, 0x50, 0xcb, 0x8b, 0xf4, 0xa5, 0x2a, 0xf5, 0x99, 0x2a,
	0x3b, 0x09, 0x4d, 0xd4, 0x6d, 0x37, 0x5d, 0xf9, 0x9e, 0x7b, 0x9d, 0xf8, 0x7c, 0xc7, 0x32, 0xc0,
	0x41, 0xb0, 0x6c, 0x94, 0x66, 0x3c, 0xe7, 0xc4, 0xd8, 0xf0, 0xf0, 0x68, 0x3f, 0x21, 0x30, 0x56,
	0x82, 0x65, 0x04, 0x83, 0x7e, 0x88, 0x42, 0x8a, 0x06, 0x68, 0xa8, 0xbb, 0xb2, 0x24, 0xdf, 0xc1,
	0x64, 0xb1, 0x1f, 0xed, 0xa9, 0x3e, 0x40, 0xc3, 0x8e, 0x5b, 0x08, 0x42, 0xa1, 0xe5, 0x07, 0x01,
	0x3f, 0x24, 0x39, 0x35, 0x54, 0xbf, 0x92, 0xe4, 0x07, 0xb4, 0x93, 0x28, 0xd8, 0x25, 0x7e, 0xcc,
	0xa8, 0xa9, 0x46, 0x27, 0x2d, 0x67, 0xa9, 0x2f, 0xc4, 0x03, 0xcf, 0x42, 0x6a, 0x15, 0xb3, 0x4a,
	0xcb, 0x73, 0xd2, 0x3b, 0x9e, 0x30, 0xda, 0x2a, 0xce, 0x51, 0xc2, 0xfe, 0x07, 0x3d, 0x97, 0x89,
	0x94, 0x27, 0x82, 0x4d, 0x78, 0xc8, 0x08, 0x01, 0x23, 0xe0, 0x21, 0x53, 0x06, 0x4d, 0x57, 0xd5,
	0xd2, 0x73, 0x2c, 0xb6, 0x54, 0x53, 0xdf, 0xc9, 0xd2, 0x7e, 0x41, 0xd0, 0x97, 0x38, 0x2e, 0xdb,
	0x46, 0x22, 0x97, 0xeb, 0x7d, 0xdd, 0x31, 0x6a, 0x3a, 0x2e, 0x99, 0xb5, 0x06, 0x73, 0xe1, 0x45,
	0xaf, 0x79, 0x21, 0x7f, 0xa0, 0xb3, 0xe7, 0xdb, 0x28, 0x59, 0x1e, 0x53, 0xa6, 0xa8, 0xbf, 0x8d,
	0xfb, 0x23, 0x19, 0xdf, 0xe8, 0xba, 0x6a, 0xbb, 0x6f, 0x3b, 0x1a, 0xb0, 0xe6, 0x7b, 0xd8, 0x9c,
	0xef, 0x58, 0x52, 0xa6, 0x50, 0x08, 0x69, 0x51, 0xc4, 0x62, 0xc9, 0x1e, 0xf3, 0x32, 0x84, 0x4a,
	0xda, 0x6b, 0xc0, 0x4d, 0x1e, 0x91, 0x92, 0x5f, 0xb5, 0x28, 0xba, 0x63, 0x52, 0x38, 0xa9, 0x87,
	0x55, 0xc6, 0xf3, 0x13, 0x0c, 0x79, 0xdf, 0x8a, 0xaf, 0x3b, 0x86, 0x62, 0x9f, 0xfa, 0x9b, 0xea,
	0xdb, 0xcf, 0x08, 0x7a, 0x52, 0x2a, 0x88, 0x4f, 0x9f, 0x94, 0x07, 0x5f, 0x6b, 0x30, 0x1f, 0x17,
	0xd3, 0xef, 0x39, 0x74, 0x4e, 0xe6, 0x49, 0x17, 0x5a, 0x2b, 0xe7, 0xca, 0x99, 0x7a, 0x0e, 0xfe,
	0x22, 0xc5, 0xff, 0xc9, 0x64, 0xba, 0x72, 0x96, 0x18, 0x91, 0x1e, 0xb4, 0x67, 0x97, 0x53, 0xe7,
	0x62, 0xe6, 0x9d, 0x63, 0xed, 0xa4, 0x16, 0x37, 0x0b, 0xac, 0x13, 0x0b, 0xb4, 0xf9, 0x1c, 0x1b,
	0x72, 0xf5, 0x6e, 0xb1, 0x79, 0x66, 0xad, 0xd5, 0xeb, 0xdb, 0x58, 0xea, 0x29, 0xfe, 0x7d, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xc5, 0xae, 0xe0, 0x29, 0x98, 0x03, 0x00, 0x00,
}
