// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_login.proto

/*
Package body is a generated protocol buffer package.

It is generated from these files:
	user_login.proto
	user_register.proto

It has these top-level messages:
	UserLogin
	UserRegister
*/
package body

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserLogin_TransferType int32

const (
	UserLogin_USERLOGINTYPEACCOUNT UserLogin_TransferType = 0
	UserLogin_USERLOGINTYPEPHONE   UserLogin_TransferType = 1
	UserLogin_USERLOGINTYPEQQ      UserLogin_TransferType = 2
	UserLogin_USERLOGINTYPEWX      UserLogin_TransferType = 3
)

var UserLogin_TransferType_name = map[int32]string{
	0: "USERLOGINTYPEACCOUNT",
	1: "USERLOGINTYPEPHONE",
	2: "USERLOGINTYPEQQ",
	3: "USERLOGINTYPEWX",
}
var UserLogin_TransferType_value = map[string]int32{
	"USERLOGINTYPEACCOUNT": 0,
	"USERLOGINTYPEPHONE":   1,
	"USERLOGINTYPEQQ":      2,
	"USERLOGINTYPEWX":      3,
}

func (x UserLogin_TransferType) String() string {
	return proto.EnumName(UserLogin_TransferType_name, int32(x))
}
func (UserLogin_TransferType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// UserLogin Server Message结构
type UserLogin struct {
	Account   string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Uid       int64  `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Phone     string `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	LoginType int32  `protobuf:"varint,4,opt,name=loginType" json:"loginType,omitempty"`
	Password  string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Token     string `protobuf:"bytes,6,opt,name=token" json:"token,omitempty"`
}

func (m *UserLogin) Reset()                    { *m = UserLogin{} }
func (m *UserLogin) String() string            { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()               {}
func (*UserLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserLogin) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserLogin) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserLogin) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *UserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*UserLogin)(nil), "body.UserLogin")
	proto.RegisterEnum("body.UserLogin_TransferType", UserLogin_TransferType_name, UserLogin_TransferType_value)
}

func init() { proto.RegisterFile("user_login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x8a, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0xca,
	0x4f, 0xa9, 0x54, 0xea, 0x64, 0xe2, 0xe2, 0x0c, 0x2d, 0x4e, 0x2d, 0xf2, 0x01, 0xc9, 0x08, 0x49,
	0x70, 0xb1, 0x27, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xc1, 0xb8, 0x42, 0x02, 0x5c, 0xcc, 0xa5, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41,
	0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x41, 0x46, 0x7e, 0x5e, 0xaa, 0x04, 0x33, 0x58, 0x25, 0x84,
	0x23, 0x24, 0xc3, 0xc5, 0x09, 0xb6, 0x24, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x45, 0x81, 0x51, 0x83,
	0x35, 0x08, 0x21, 0x20, 0x24, 0xc5, 0xc5, 0x51, 0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x5f, 0x94, 0x22,
	0xc1, 0x0a, 0xd6, 0x06, 0xe7, 0x83, 0xcc, 0x2b, 0xc9, 0xcf, 0x4e, 0xcd, 0x93, 0x60, 0x83, 0x98,
	0x07, 0xe6, 0x28, 0x65, 0x71, 0xf1, 0x84, 0x14, 0x25, 0xe6, 0x15, 0xa7, 0xa5, 0x16, 0x81, 0x4d,
	0x90, 0xe0, 0x12, 0x09, 0x0d, 0x76, 0x0d, 0xf2, 0xf1, 0x77, 0xf7, 0xf4, 0x0b, 0x89, 0x0c, 0x70,
	0x75, 0x74, 0x76, 0xf6, 0x0f, 0xf5, 0x0b, 0x11, 0x60, 0x10, 0x12, 0xe3, 0x12, 0x42, 0x91, 0x09,
	0xf0, 0xf0, 0xf7, 0x73, 0x15, 0x60, 0x14, 0x12, 0xe6, 0xe2, 0x47, 0x11, 0x0f, 0x0c, 0x14, 0x60,
	0xc2, 0x10, 0x0c, 0x8f, 0x10, 0x60, 0x76, 0x62, 0x8b, 0x02, 0x87, 0x49, 0x12, 0x1b, 0x38, 0x80,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x31, 0x0b, 0xaf, 0x34, 0x01, 0x00, 0x00,
}
